name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: alanzit0x
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alanzit0x/go_ci:${{ github.ref_name }}
